source('F:/Richard/PARAFAC/Code R/myPalette.R')
 source('F:/Richard/PARAFAC/Code R/NanoMean.R')
 source('F:/Richard/PARAFAC/Code R/InnerFilter.R')
 source('F:/Richard/PARAFAC/Code R/PARAFAC.cube.design.R')
 source('F:/Richard/PARAFAC/Code R/plot.eem.go.richard.R')
 source('F:/Richard/PARAFAC/Code R/plot.integrate.RAMAN.R')
 source('F:/Richard/PARAFAC/Code R/read.EEM.Richard.R')
 source('F:/Richard/PARAFAC/Code R/subtract.blank.plot.EEMs.Richard.R')
 source('F:/Richard/PARAFAC/Code R/plot.integrate.RAMAN.go.R')
require(stringr)
